### ISSUE TITLE
Discord Support, or Discord Embed Support at least

### ISSUE THREAD

**Issue by jay3332** [JonSnowbd/TagScript#14]
If possible, maybe make the `process` function have a `ctx` parameter which takes in a discord.Context object or something along the lines of that, allowing things like
`{embed(title):Title} {embed(description):This is an embed.}`
`Hello, {user(name)}!`
`{target(user)} has {range:1-200} IQ.`
`{del}I deleted your message.`

As I know you have them in Carl-bot.
Of course, leave out the impossible scenarios, e.g. the {cmd} block

**Comment by JonSnowbd** [comment]
Hi! Absolutely possible using this library to create an adapter to use in place without modifying anything. 

[An example](https://github.com/JonSnowbd/TagScript/blob/v2/TagScriptEngine/adapter/stringadapter.py)

All is needed is a `get_value(Verb)` method that will resolve the adapter into a string. In place of this in your case, youre going to need to have an adapter that returns `""` so that it will be replaced with nothing, then mutate your inner discord settings. Or in the case of retrieving names, query your state for user id -> name lookups.

After you have an adapter you can then feed it into the engine [like so](https://github.com/JonSnowbd/TagScript/blob/v2/Tests/test_adapters.py#L19) where `data` is the dictionary of your adapters that you have created.

It's been a while since I looked over the codebase and just skimmed over it the past few minutes, if anything needs deeper explaining just let me know.

**Comment by jay3332** [comment]
Thanks for responding so fast!

So do I have to make a new `discordadapter.py` file, that returns `""`? And I'm kind of confused on what to do with the empty string if so.

**Comment by JonSnowbd** [comment]
you dont need to do anything with the empty string, returning an empty string means the `{discord(whatver)}` call in the input string gets replaced with nothing, removing it from the input if its a call that doesnt need to put something there, like delete.

What you need is adapters for each type you want, users needs an adapter, and commands each need their adapter preferably.

For example, `NameAdapter`, intended to be used as `{name(user)}` or `{name(target)}` would be in pseudo code
```
if verb.parameter == "user" return DiscordContext.GetUserName(message.UserID)
if verb.parameter == "target return DiscordContext.GetUserName(message.FirstPinged.UserID)

return "" # none of the above returns empty, replacing with nothing
```
in commands just return `""` after mutating your bot to make it modify the message
eg deleting it, adding an embed to the response, preventing a message entirely etc.
